
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "**/*_spec.rb"
  
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/AbcSize:
  Enabled: true
  Max: 25